package beta;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.Scanner;

/*
 * This class reads the text file of ballots generated by
 * the online form and returns a list of all candidates names contained in the file
*/
public class VoteTools
{

	public static ArrayList<String> makeCandidateList(String fileName)
	{
		FileReader file = null;
		try
		{
			file = new FileReader(fileName);
		}
		catch (FileNotFoundException e)
		{
			e.printStackTrace();
		}
		Scanner fileScanner = new Scanner(file);
		fileScanner.nextLine(); // throw away header (first line)
		String line;
		ArrayList<String> nameList = new ArrayList<String>();
		
		while (fileScanner.hasNextLine())
		{
			line = fileScanner.nextLine();
			ArrayList<String> lineTokenized = tokenizeString(line, ',');
			lineTokenized.remove(0);
			for (String name : lineTokenized)
			{
				if (name.length() > 0 && !nameList.contains(name))
				{
					nameList.add(name);
				}
			}	
		}
		
		fileScanner.close();
		
		return nameList;
	}

	/**
	 * This method tokenizes a String based on a character delimiter
	 * @param line - the string to be tokenized
	 * @param delimiter - a single character delimiter
	 * @return - an ArrayList of String tokens
	 */
	public static ArrayList<String> tokenizeString(String line, char delimiter)
	{
		ArrayList<String> tokens = new ArrayList<String>();
		int start = 0;
		int end = line.indexOf(delimiter);
		while (end != -1)
		{
			tokens.add(line.substring(start, end));
			start = end + 1;
			end = line.indexOf(delimiter, start);
		}
		tokens.add(line.substring(start));
		return tokens;
	}

}
